In [2]:
import numpy as np
import torch

## Tensor

In [3]:
scalar = torch.tensor(3.14159)
vector = torch.tensor([1, 2, 3])
matrix = torch.ones((2, 3), dtype=torch.float)
tensor = torch.randn((2, 3, 4), dtype=torch.float)

print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(3.1416)
tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[ 1.0402,  2.1332,  1.2022,  0.4409],
         [-0.4151,  1.1729, -1.3006, -1.3797],
         [ 0.1040, -0.7186,  1.1337,  1.1479]],

        [[ 1.4629, -2.1166,  1.7661, -0.5944],
         [-0.6659,  1.0553,  1.7491,  0.5463],
         [ 1.1368,  1.1792,  1.3142,  0.9795]]])
