In [2]:
import numpy as np
import torch

## Tensor

In [3]:
scalar = torch.tensor(3.14159)
vector = torch.tensor([1, 2, 3])
matrix = torch.ones((2, 3), dtype=torch.float)
tensor = torch.randn((2, 3, 4), dtype=torch.float)

print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(3.1416)
tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[ 0.4491, -0.4545,  0.7688, -1.1622],
         [ 0.8552, -0.2642,  0.5951, -1.1271],
         [-0.3165, -1.1745, -0.0240, -0.2610]],

        [[ 1.1852,  0.1704, -0.1652, -0.3403],
         [ 0.9745,  1.1581, -0.3177,  1.8837],
         [ 1.7287,  0.2592, -1.2862,  0.6317]]])
