In [4]:
import numpy as np
import torch

## Tensor

In [5]:
scalar = torch.tensor(3.14159)
vector = torch.tensor([1, 2, 3])
matrix = torch.ones((2, 3), dtype=torch.float)
tensor = torch.randn((2, 3, 4), dtype=torch.float)

print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(3.1416)
tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[ 0.8715, -0.8096, -1.3238, -0.1266],
         [ 0.2257,  0.8395,  1.4724, -2.7485],
         [ 0.7625, -0.4212, -0.6294,  1.3727]],

        [[-0.4907,  1.9774,  1.0172,  0.6173],
         [-0.3489,  0.2082, -0.0590, -1.7912],
         [ 1.6961,  0.0756, -0.1325, -1.8283]]])


In [6]:
print(tensor.size(), tensor.shape)

torch.Size([2, 3, 4]) torch.Size([2, 3, 4])


In [7]:
print(scalar.size(), scalar.shape)

torch.Size([]) torch.Size([])


In [8]:
# We get a tensor with a different shape but it still is
# the SAME tensor
same_matrix = matrix.view(1, 6)
# If we change one of its elements...
same_matrix[0, 1] = 2.
# It changes both variables: matrix and same_matrix
print(matrix)
print(same_matrix)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 2., 1., 1., 1., 1.]])


In [9]:
# Let's follow PyTorch's suggestion and use "clone" method
another_matrix = matrix.view(1, 6).clone().detach()
# Again, if we change one of its elements...
another_matrix[0, 1] = 4.
# The original tensor (matrix) is left untouched!
print(matrix)
print(another_matrix)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 4., 1., 1., 1., 1.]])
